### ISSUE TITLE
Get error from sample_judge.py

### ISSUE THREAD

**Issue by DjengoFang** [NTU-SP/SP-Hw1-release#23]
I run the command "python sample_judge.py". And get the following error. What shall I do?

File "sample_judge.py", line 23
    print(f"Client {self.client_idx} connects to {self.server_type.lower()} {self.server_idx}")
                                                                                             ^
SyntaxError: invalid syntax

**Comment by imingasco** [comment]
Maybe you accidentally modified sample judge?

**Comment by DjengoFang** [comment]
> Maybe you accidentally modified sample judge?

我剛剛直接複製貼上[SP-Hw1-release](https://github.com/NTU-SP/SP-Hw1-release)的sample judge.py還是出現一樣的問題
會不會是使用mac的問題？

**Comment by imingasco** [comment]
你是在 linux1 上跑嗎？不是的話用 `python -V` 看一下版本是不是 3.9+，可能是 python 版本問題導致的。

**Comment by DjengoFang** [comment]
用 python3 sample_judge.py 指令就解決了
