### ISSUE TITLE
Ｗhat does this mean by auto grading?

### ISSUE THREAD

**Issue by DjengoFang** [NTU-SP/SP-Hw1-release#28]
After I pushed the code onto GIthub, my auto grading show the following message under each subtask. What does this mean?
<img width="1440" alt="Screen Shot 2022-10-09 at 9 18 58 AM" src="https://user-images.githubusercontent.com/103123107/194733116-7ffb2cdd-6fab-4b63-8e63-de65c63ffbdb.png">

**Comment by imingasco** [comment]
It seems that your server was closed before an operation was finished.

**Comment by DjengoFang** [comment]
Got it. Thanks.
