### ISSUE TITLE
How to test Makefile?

### ISSUE THREAD

**Issue by DjengoFang** [NTU-SP/SP-Hw1-release#44]
If my code passed the sample judge, does that means my Makefile is correct?
What other commands besides "make" and "make clean" should we test?

**Comment by imingasco** [comment]
If you passed the sample judge, your `make` command is correct.
If your `make clean` is not correct, your points will be deducted and a message will be printed.

**Comment by DjengoFang** [comment]
Got it. Thank you very much.
